-- ==============================================================================
-- SCRIPT SETUP BOT WHATSAPP OTOMATIS (SUPABASE CLOUD)
-- Menggunakan pg_net (HTTP API) dan pg_cron (Penjadwalan)
-- ==============================================================================

-- 1. Aktifkan ekstensi yang dibutuhkan (Hanya bisa dijalankan oleh Superuser)
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- 2. Buat fungsi untuk menarik data dan mengirim pesan ke Fonnte
CREATE OR REPLACE FUNCTION public.send_daily_wa_report(
    p_email TEXT, 
    p_target TEXT, 
    p_token TEXT
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id UUID;
    v_income DECIMAL(15,2) := 0;
    v_expense DECIMAL(15,2) := 0;
    v_balance DECIMAL(15,2) := 0;
    v_message TEXT;
    v_request_body JSONB;
BEGIN
    -- Cari ID User berdasarkan Email
    SELECT id INTO v_user_id FROM auth.users WHERE email = p_email LIMIT 1;
    
    IF v_user_id IS NULL THEN
        RAISE NOTICE 'User dengan email % tidak ditemukan', p_email;
        RETURN;
    END IF;

    -- Hitung Pemasukan Hari Ini
    SELECT COALESCE(SUM(amount), 0) INTO v_income
    FROM public.transactions
    WHERE user_id = v_user_id AND type = 'income' AND date = CURRENT_DATE;

    -- Hitung Pengeluaran Hari Ini
    SELECT COALESCE(SUM(amount), 0) INTO v_expense
    FROM public.transactions
    WHERE user_id = v_user_id AND type = 'expense' AND date = CURRENT_DATE;

    -- Hitung Saldo Sisa Hari Ini
    v_balance := v_income - v_expense;

    -- Susun Pesan (menggunakan chr(10) untuk enter/baris baru)
    v_message := '*Laporan Keuangan Hari Ini* 📊' || chr(10) || chr(10) ||
                 'Pemasukan : Rp ' || to_char(v_income, 'FM999G999G999G999') || chr(10) ||
                 'Pengeluaran : Rp ' || to_char(v_expense, 'FM999G999G999G999') || chr(10) ||
                 'Saldo Sisa : Rp ' || to_char(v_balance, 'FM999G999G999G999') || chr(10) || chr(10) ||
                 '_Auto-generated by Annida2Finance_';

    -- Siapkan Payload JSON untuk dikirim ke API Fonnte
    v_request_body := jsonb_build_object(
        'target', p_target,
        'message', v_message
    );

    -- Tembak API Fonnte menggunakan pg_net
    PERFORM net.http_post(
        url := 'https://api.fonnte.com/send',
        headers := jsonb_build_object(
            'Authorization', p_token,
            'Content-Type', 'application/json'
        ),
        body := v_request_body
    );
END;
$$;

-- ==============================================================================
-- CARA MENGGUNAKAN (JALANKAN KODE DI BAWAH INI SETELAH ANDA MENDAPATKAN TOKEN):
-- ==============================================================================

/*
-- Hapus jadwal lama jika ada (opsional)
SELECT cron.unschedule('laporan_keuangan_harian');

-- Buat jadwal baru (Berjalan setiap jam 17:00 waktu server GMT, atau sesuaikan)
-- Ganti 'admin@admin.com', 'NOMOR_HP_GRUP', dan 'TOKEN_FONNTE_ANDA' dengan yang asli.
SELECT cron.schedule(
    'laporan_keuangan_harian', 
    '0 10 * * *', -- Jam 10:00 GMT = 17:00 WIB (Waktu Indonesia Barat)
    $$SELECT public.send_daily_wa_report('admin@admin.com', '081234567890', 'TOKEN_FONNTE_ANDA')$$
);
*/
